### ISSUE TITLE
Challenge 2 - troubleshooting section lacks details

### ISSUE THREAD

**Issue by gdusart** [kodekloudhub/kubernetes-challenges#5]
Troubleshooting section for challenge 2 seems to be targeting CKA students, not CKAD.

Information currently provided on this repository is lacking some details and some students (like me) are stuck. (e.g.:  https://www.udemy.com/course/certified-kubernetes-application-developer/learn/lecture/13302768#questions/17630214) 

A more detailed guide is provided on your community forums: https://community.kodekloud.com/t/kubernetes-challenge-2/125431/9

Merging the detailed guide from this forum into git would be appreciated.

Thanks

**Comment by Tej-Singh-Rana** [comment]
Hi @gdusart ,
Thanks for your feedback. We will try to merge it into this repo. 

Regards,

**Comment by fireflycons** [comment]
Hi @gdusart 
I see it's my detailed instructions you're referring to. It's on my todo list to update this repo!

**Comment by Tej-Singh-Rana** [comment]
@fireflycons has added detailed solution. Please check again whenever you get a chance.  👍
