### ISSUE TITLE
Challenge 3 has missing information for db-deployment and worker deployment

### ISSUE THREAD

**Issue by khanmshariq** [kodekloudhub/kubernetes-challenges#6]
With the given specs, the db-deployment pod and worker pod is not coming in running state. On checking the solution, an environment variable is set in db-deployment yaml, there is no such info given in task. Please check and anticipate.

Thanks
Shariq

![db-deployment](https://user-images.githubusercontent.com/110946070/186709276-612f1b5f-4bd1-4814-8bcc-ba96407e9756.PNG)
![worker](https://user-images.githubusercontent.com/110946070/186709286-f5e9f457-1759-45a3-ab7c-0e1036d6b0d2.PNG)

**Comment by Tej-Singh-Rana** [comment]
Hi @khanmshariq,
One of our team members has added detailed solution. Please try again with the lab when you get a chance. 👍 

Regards,
